import {
  authenticate,
  cancelOrders,
  listClearedOrders,
  listCompetitions,
  listCountries,
  listCurrentOrders,
  listEvents,
  listEventTypes,
  listMarketBook,
  listMarketCatalogue,
  listMarketProfitAndLoss,
  listMarketTypes,
  listRunnerBook,
  listTimeRanges,
  listVenues,
  replaceOrders,
  placeOrders,
} from './bettingAPI';

export {
  authenticate,
  cancelOrders,
  listClearedOrders,
  listCompetitions,
  listCountries,
  listCurrentOrders,
  listEvents,
  listEventTypes,
  listMarketBook,
  listMarketCatalogue,
  listMarketProfitAndLoss,
  listMarketTypes,
  listRunnerBook,
  listTimeRanges,
  listVenues,
  replaceOrders,
  placeOrders,
};
